### ISSUE TITLE
curl should include -L in startserver.sh script

### ISSUE THREAD

**Issue by therealeldaria** [TeamAOF/All-of-Fabric-5#180]
Hello.

In the file startserver.sh where it tries to download serverstarter-2.1.1.jar
The curl options are missing -L causing the script to download html instead of the jar file as the link is redirected.

**Comment by F1r3w477** [comment]
This was fixed in 40f4230e9b866211ae5c976a0cf1546302d2da9a I would assume it will be available in the next update.

**Comment by therealeldaria** [comment]
I just tried to install the latest 1.3.1 release, and the -L option is still not in the startserver.sh so it fails to download the serverstarter.2.4.0.jar

**Comment by unilock** [comment]
startserver.sh is no longer included as of https://github.com/TeamAOF/All-of-Fabric-5/commit/5ccb6b6f0a3126cf09a63bd1344c5de909be90cc, but it's still included in the server packs on CurseForge - so I'm not really sure what's going on here??
